#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    fortune -s
    print
  fi
} >&2

# Local machine specific login shell setup that we don't want to commit to source control
if [[ -f ~/.zlogin.local ]]; then
    source ~/.zlogin.local
fi

# All linux machines regardless of host - ensure fixed annoying <Super+P> key combo setting projector mode
# which interferes with the i3 WM shortcuts
[[ `uname` = Linux ]] && which dconf > /dev/null && dconf write /org/gnome/settings-daemon/plugins/media-keys/active false

