#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export PATH="$PATH:/opt/perforce/p4/bin"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$PATH:$HOME/bin"
typeset -U PATH

alias c=colorize_via_pygmentize
alias hadoop='nocorrect hadoop'
alias hi='rlwrap --always-readline -t dumb hive'
alias hl='hdfs dfs -ls'
alias xclip='xclip -selection c'

function cl() {
FILENAMES=("$@")
    colorize $FILENAMES | less
}

function git_permission_reset() {
    git diff -p -R | grep -E "^(diff|(old|new) mode)" | git apply
}

# ghc-pkg-reset
# Removes all installed GHC/cabal packages, but not binaries, docs, etc.
# Use this to get out of dependency hell and start over, at the cost of some rebuilding time.
function ghc-pkg-reset() {
    # bash: read -p 'erasing all your user ghc and cabal packages - are you sure (y/n) ? ' ans
    read -q "ans?Erasing all your user ghc and cabal packages - are you sure (y/n) ?"
    [[ $ans == 'y' ]] && ( \
        echo 'erasing directories under ~/.ghc'; rm -rf `find ~/.ghc -maxdepth 1 -type d`; \
        echo 'erasing ~/.cabal/lib'; rm -rf ~/.cabal/lib; \
        echo 'erasing ~/.cabal/packages'; rm -rf ~/.cabal/packages; \
        echo 'erasing ~/.cabal/share'; rm -rf ~/.cabal/share; \
        )
}

# Local machine specific shell setup that we don't want to commit to source control
if [[ -f ~/.rc.local ]]; then
    source ~/.rc.local
fi
